//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.20 at 11:28:20 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.dam.igate.com/Checksum/")
package com.igate.dam.checksum.dto;
