//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.20 at 11:28:20 AM IST 
//


package com.igate.dam.checksum;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="userFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="md5alueFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "userFile",
    "md5AlueFile"
})
@XmlRootElement(name = "user")
public class User {

    @XmlElement(required = true)
    protected String userFile;
    @XmlElement(name = "md5alueFile", required = true)
    protected String md5AlueFile;

    /**
     * Gets the value of the userFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserFile() {
        return userFile;
    }

    /**
     * Sets the value of the userFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserFile(String value) {
        this.userFile = value;
    }

    /**
     * Gets the value of the md5AlueFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMd5AlueFile() {
        return md5AlueFile;
    }

    /**
     * Sets the value of the md5AlueFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMd5AlueFile(String value) {
        this.md5AlueFile = value;
    }

}
