//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.14 at 06:53:52 PM IST 
//


package com.igate.dam.dynamic.workflow.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.igate.dynamic.workflow.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.igate.dynamic.workflow.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TriggerDynamicWorkFlowRequest }
     * 
     */
    public TriggerDynamicWorkFlowRequest createTriggerDynamicWorkFlowRequest() {
        return new TriggerDynamicWorkFlowRequest();
    }

    /**
     * Create an instance of {@link TriggerDynamicWorkFlowResponse }
     * 
     */
    public TriggerDynamicWorkFlowResponse createTriggerDynamicWorkFlowResponse() {
        return new TriggerDynamicWorkFlowResponse();
    }

    /**
     * Create an instance of {@link TriggerDynamicWorkFlowRequest.SupplierDetails }
     * 
     */
    public TriggerDynamicWorkFlowRequest.SupplierDetails createTriggerDynamicWorkFlowRequestSupplierDetails() {
        return new TriggerDynamicWorkFlowRequest.SupplierDetails();
    }

}
