//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.14 at 06:53:52 PM IST 
//


package com.igate.dam.dynamic.workflow.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="processinstanceid" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="invocationsuccess" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "processinstanceid",
    "invocationsuccess"
})
@XmlRootElement(name = "TriggerDynamicWorkFlowResponse")
public class TriggerDynamicWorkFlowResponse {

    protected int processinstanceid;
    protected boolean invocationsuccess;

    /**
     * Gets the value of the processinstanceid property.
     * 
     */
    public int getProcessinstanceid() {
        return processinstanceid;
    }

    /**
     * Sets the value of the processinstanceid property.
     * 
     */
    public void setProcessinstanceid(int value) {
        this.processinstanceid = value;
    }

    /**
     * Gets the value of the invocationsuccess property.
     * 
     */
    public boolean isInvocationsuccess() {
        return invocationsuccess;
    }

    /**
     * Sets the value of the invocationsuccess property.
     * 
     */
    public void setInvocationsuccess(boolean value) {
        this.invocationsuccess = value;
    }

}
