//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.14 at 06:53:52 PM IST 
//


package com.igate.dam.dynamic.workflow.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SupplierDetails">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="suppid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="suppname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="currstep" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "supplierDetails"
})
@XmlRootElement(name = "TriggerDynamicWorkFlowRequest")
public class TriggerDynamicWorkFlowRequest {

    @XmlElement(name = "SupplierDetails", required = true)
    protected TriggerDynamicWorkFlowRequest.SupplierDetails supplierDetails;

    /**
     * Gets the value of the supplierDetails property.
     * 
     * @return
     *     possible object is
     *     {@link TriggerDynamicWorkFlowRequest.SupplierDetails }
     *     
     */
    public TriggerDynamicWorkFlowRequest.SupplierDetails getSupplierDetails() {
        return supplierDetails;
    }

    /**
     * Sets the value of the supplierDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link TriggerDynamicWorkFlowRequest.SupplierDetails }
     *     
     */
    public void setSupplierDetails(TriggerDynamicWorkFlowRequest.SupplierDetails value) {
        this.supplierDetails = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="suppid" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="suppname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="currstep" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "suppid",
        "suppname",
        "currstep"
    })
    public static class SupplierDetails {

        @XmlElement(required = true)
        protected String suppid;
        @XmlElement(required = true)
        protected String suppname;
        @XmlElement(required = true)
        protected String currstep;

        /**
         * Gets the value of the suppid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSuppid() {
            return suppid;
        }

        /**
         * Sets the value of the suppid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSuppid(String value) {
            this.suppid = value;
        }

        /**
         * Gets the value of the suppname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSuppname() {
            return suppname;
        }

        /**
         * Sets the value of the suppname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSuppname(String value) {
            this.suppname = value;
        }

        /**
         * Gets the value of the currstep property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCurrstep() {
            return currstep;
        }

        /**
         * Sets the value of the currstep property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCurrstep(String value) {
            this.currstep = value;
        }

    }

}
